### PR TITLE
adding toml files

### PR DESCRIPTION
**Pull request by dehann**

### CODE REVIEW

**Comment by dehann** [comment]
travis stuck on Pkg not finding `LinearAlgebra` in dependencies??

**Comment by dehann** [comment]
cc @Affie

**Comment by dehann** [comment]
used this function
https://discourse.julialang.org/t/convert-require-to-project-toml-and-manifest-toml/17775/2

but then had an issue with LinearAlgebra as dependency with Travis...

One suggestion is to do this first:
```julia
] activate .
add LinearAlgebra
```

**Comment by Affie** [comment]
yes, cd to project files.
```julia
] activate .
test # see what dependencies fail
add LinearAlgebra # add dependancies that was not found
```

**Pull request merged**
